--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BrahmjotSingh0/Portals
build-by-default: true
branches:
- main
projects:
  Portals:
    path: ""
    libs: 
     - src: Paroxity/Commando/Commando
       version: ^3.2.1
     - src: poggit/libasynql/libasynql
       version: ^4.1.6
     - src: sof3/await-generator/await-generator
       version: ^3.1.0
...
