name: Portals
main: BrahmjotSingh0\Portals\Portals
version: 3.0.0
api: [5.3.0]
author: BrahmjotSingh0
permissions:
  portals.command:
    description: Allows the player to use the portal commands
    default: op
  portals.addcommand:
    default: op
  portals.delete:
    default: op
  portals.create:
    default: op
  portals.list:
    default: op
  portals.pos1:
    default: op
  portals.pos2:
    default: op
  portals.msg:
    default: op
